spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcon?createTableIfNotExists=true
    username: root
    password: mysql@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
  jba:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
welcome:
  message: Welcome to Spring Boot Application
